const CartActionTypes = {
    TOGGLE_CART_HIDDEN : 'TOGGLE_CART_HIDDEN',
    ADD_ITEM_TO_CART: 'ADD_ITEM_TO_CART',
    REMOVE_ITEM_FROM_CART: 'REMOVE_ITEM_FROM_CART',
    INCREMENT_CART_ITEM_QUANTITY: 'INCREMENT_CART_ITEM_QUANTITY',
    DECREMENT_CART_ITEM_QUANTITY: 'DECREMENT_CART_ITEM_QUANTITY'
}

export default CartActionTypes